# Generated by Django 2.1.8 on 2019-05-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_registeration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='address1',
            field=models.IntegerField(choices=[(0, '강남구'), (1, '강동구'), (2, '강북구'), (3, '강서구'), (4, '관악구'), (5, '광진구'), (6, '구로구'), (7, '금천구'), (8, '노원구'), (9, '도봉구'), (10, '동대문구'), (11, '동작구'), (12, '마포구'), (13, '서대문구'), (14, '서초구'), (15, '성동구'), (16, '성북구'), (17, '송파구'), (18, '양천구'), (19, '영등포구'), (20, '용산구'), (21, '은평구'), (22, '종로구'), (23, '중구'), (24, '중랑구')], null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='address2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='deadline',
            field=models.DateTimeField(verbose_name='data published'),
        ),
    ]
